repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: ./venv/Scripts/isort.exe
        language: python
        types: [python]


-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: ./venv/Scripts/flake8.exe
        args: ["--config=setup.cfg"]
        language: python
        types: [python]



-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: ./venv/Scripts/mypy.exe
        language: python
        types: [python]

