services:
    postgres:
        image: postgres:latest
        container_name: postgresql_test
        environment:  # Измените 'env' на 'environment'
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test_db
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
        ports:
            - "5432:5432"
