services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        env_file:
            - .env-dev
        ports:
            - "5432:5432"

    cats_service:
        container_name: cats_service
        build:
            context: ./
            dockerfile: Dockerfile
        command: poetry run uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        env_file:
            - .env-dev 
        ports:
            - "8000:8000"
